<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>DragNWashLocalization</AssemblyName>
    <RootNamespace>DragNWashLocalization</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>D:\SteamLibrary\steamapps\common\Drag'n Wash\DragNWash_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>D:\SteamLibrary\steamapps\common\Drag'n Wash\DragNWash_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>D:\SteamLibrary\steamapps\common\Drag'n Wash\DragNWash_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>D:\SteamLibrary\steamapps\common\Drag'n Wash\DragNWash_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>D:\SteamLibrary\steamapps\common\Drag'n Wash\DragNWash_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>D:\SteamLibrary\steamapps\common\Drag'n Wash\DragNWash_Data\Managed\Unity.TextMeshPro.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>D:\SteamLibrary\steamapps\common\Drag'n Wash\DragNWash_Data\Managed\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.TextCoreTextEngineModule">
      <HintPath>D:\SteamLibrary\steamapps\common\Drag'n Wash\DragNWash_Data\Managed\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="YarnSpinner">
      <HintPath>D:\SteamLibrary\steamapps\common\Drag'n Wash\DragNWash_Data\Managed\YarnSpinner.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="YarnSpinner.Unity">
      <HintPath>D:\SteamLibrary\steamapps\common\Drag'n Wash\DragNWash_Data\Managed\YarnSpinner.Unity.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>D:\SteamLibrary\steamapps\common\Drag'n Wash\DragNWash_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>D:\SteamLibrary\steamapps\common\Drag'n Wash\DragNWash_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>D:\SteamLibrary\steamapps\common\Drag'n Wash\DragNWash_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="NaelstrofRaliv.DynamicPenetrationForGames">
      <HintPath>D:\SteamLibrary\steamapps\common\Drag'n Wash\DragNWash_Data\Managed\NaelstrofRaliv.DynamicPenetrationForGames.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>..\lib\0Harmony.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

</Project>
